# Generated by Django 3.1.7 on 2021-12-18 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("time_tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="week",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="day",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="day",
            name="week",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="time_tracking.week"
            ),
        ),
    ]
