# Generated by Django 3.1.7 on 2021-12-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("time_tracking", "0002_auto_20211218_0822"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="day_of_week",
            field=models.IntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="week",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=230, max_digits=5),
            preserve_default=False,
        ),
    ]
