# Generated by Django 3.1.7 on 2021-12-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("time_tracking", "0003_auto_20211218_0856"),
    ]

    operations = [
        migrations.AddField(
            model_name="week",
            name="weight_recorded",
            field=models.BooleanField(default=False),
        ),
    ]
