# Generated by Django 3.1.7 on 2021-12-18 20:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("time_tracking", "0004_week_weight_recorded"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="day",
            unique_together={("user_id", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="week",
            unique_together={("user_id", "start_date")},
        ),
    ]
