# Generated by Django 3.1.7 on 2021-12-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("time_tracking", "0005_auto_20211218_1511"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
