# Generated by Django 3.1.7 on 2021-12-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("time_tracking", "0007_auto_20211218_1559"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
