"""Trying to set up week table with User foreign key relationship

Revision ID: ad5bd4d60045
Revises: 1f73ecb14510
Create Date: 2021-11-27 18:43:15.931121

"""
from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy import GUID


# revision identifiers, used by Alembic.
revision = 'ad5bd4d60045'
down_revision = '1f73ecb14510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('week',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('points_remaining', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('user_id', GUID, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('week')
    # ### end Alembic commands ###
