# Generated by Django 3.1.7 on 2021-11-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="token",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="token_expiration",
            field=models.DateTimeField(null=True),
        ),
    ]
