# Generated by Django 3.1.7 on 2021-12-16 20:22

from django.db import migrations, models
import weight_points_server.user.utils


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="token",
            field=models.CharField(
                blank=True,
                default=weight_points_server.user.utils.create_token,
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="token_expiration",
            field=models.DateTimeField(
                blank=True,
                default=weight_points_server.user.utils.create_token_expiration,
                null=True,
            ),
        ),
    ]
