# Generated by Django 3.1.7 on 2021-12-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_auto_20211216_1522"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="old_email",
            field=models.EmailField(
                blank=True,
                help_text='This is only used in the case where a user is updating an email address. In this case the "current" email address becomes the old one and the new email address moves into the general email field, while being set as invalid.',
                max_length=254,
                null=True,
                verbose_name="old email address",
            ),
        ),
    ]
