# Generated by Django 3.1.7 on 2021-12-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_auto_20211218_1315"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="nursing",
            field=models.IntegerField(
                choices=[(0, "None"), (1, "Supplemental"), (2, "Exclusive")], default=0
            ),
        ),
    ]
