# Generated by Django 3.1.7 on 2021-12-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_customuser_old_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="message_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("registration", "Registration"),
                    ("registration_confirm", "Registration Confirmation"),
                    ("password_forgot", "Forgot Password"),
                    ("password_change_confirm", "Password Change Confirmation"),
                    ("change_email", "Change Email"),
                    ("change_email_confirm", "Email Change Confirmation"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
