# Generated by Django 3.1.7 on 2021-12-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food_tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="notes",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name="FoodInstance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                ("quantity_string", models.CharField(max_length=16)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_tracking.food",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_tracking.meal",
                    ),
                ),
            ],
        ),
    ]
