# Generated by Django 3.1.7 on 2021-12-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_tracking", "0002_auto_20211219_1143"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodinstance",
            name="points",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
