# Generated by Django 3.1.7 on 2021-12-20 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("food_tracking", "0003_foodinstance_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.customuser",
            ),
            preserve_default=False,
        ),
    ]
