# Generated by Django 3.1.7 on 2021-12-20 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food_tracking", "0004_meal_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodinstance",
            name="meal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food",
                to="food_tracking.meal",
            ),
        ),
    ]
