# Generated by Django 3.1.7 on 2021-12-20 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food_tracking", "0005_auto_20211220_1751"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodinstance",
            name="meal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="food_tracking.meal"
            ),
        ),
    ]
