# Generated by Django 3.1.7 on 2021-12-27 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food_tracking", "0006_auto_20211220_1804"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodinstance",
            name="meal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="food_tracking.meal",
            ),
        ),
        migrations.AlterField(
            model_name="foodinstance",
            name="points",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
