# Generated by Django 3.1.7 on 2021-12-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_tracking", "0007_auto_20211226_2040"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="points",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
