# Generated by Django 3.1.7 on 2021-12-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_tracking", "0009_auto_20211227_1338"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="serving_unit",
            field=models.CharField(max_length=32),
        ),
    ]
