# Generated by Django 3.1.7 on 2021-12-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_tracking", "0010_auto_20211227_1339"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="serving_unit",
            field=models.CharField(
                choices=[
                    ("KG", "kg"),
                    ("GM", "g"),
                    ("OZ", "oz"),
                    ("LB", "lb"),
                    ("TSP", "tsp"),
                    ("TBSP", "tbsp"),
                    ("FLOZ", "fl oz"),
                    ("CUP", "cup"),
                    ("ML", "ml"),
                    ("L", "l"),
                ],
                max_length=32,
            ),
        ),
    ]
