# Generated by Django 3.1.7 on 2021-12-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_tracking", "0011_auto_20211227_1340"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodinstance",
            name="meal",
        ),
        migrations.AddField(
            model_name="foodinstance",
            name="meal",
            field=models.ManyToManyField(
                blank=True, null=True, to="food_tracking.Meal"
            ),
        ),
    ]
