# Generated by Django 3.1.7 on 2021-12-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_tracking", "0012_auto_20211227_1603"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodinstance",
            name="meal",
            field=models.ManyToManyField(to="food_tracking.Meal"),
        ),
    ]
